### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 2661348402** [roborescue/adf-sample-agent-java#16] opened 2022-04-01 09:13 UTC
In the new version of adf-sample-agent-java, there are only a few classes left in the figure below. Where can we see the modules such as centralized, extension, tactics, and module?
![图片](https://user-images.githubusercontent.com/80761477/161233321-c1c85e0a-279a-4804-b5e2-df955b473342.png)
![图片](https://user-images.githubusercontent.com/80761477/161233469-b875ddf6-6f89-4650-a37d-ea51cac64816.png)

**Comment by gnardin** [comment] 2022-04-04 05:53
Dear @2661348402 
All these modules are under the `adf.impl` package in the `adf-core-java` library.
Note that the name of the classes changed from `adf.team.module.complex.SampleAmbulanceTargetAllocator` to `adf.impl.complex.DefaultAmbulanceTargetAllocator`.
Please let me know if you need any further information.

**Comment by 2661348402** [comment] 2022-04-05 08:51
> 亲爱 的@2661348402 所有这些模块都在 `adf.impl`包在 `adf-core-java`图书馆。 请注意，类的名称从 `adf.team.module.complex.SampleAmbulanceTargetAllocator`到 `adf.impl.complex.DefaultAmbulanceTargetAllocator`. 如果您需要任何进一步的信息，请告诉我。
I downloaded the code from https://github.com/roborescue/adf-core-java, but if I copy the code directly to the src folder of the adf-sample-agent-java project, the idea cannot be compiled successfully , then how do I put the code into the adf-sample-agent-java project

**Comment by 2661348402** [comment] 2022-04-05 09:19
I downloaded the code from https://github.com/roborescue/adf-core-java, but if I copy the code directly to the src folder of the adf-sample-agent-java project, the idea cannot be compiled successfully , then how do I put the code into the adf-sample-agent-java project

**Comment by gnardin** [comment] 2022-04-05 11:06
Dear @2661348402 
You do not need to copy the code from `adf-core-java` to `adf-sample-agent-java`, you can refer to them in the `config/module.cfg` file. For example, if you want to use `adf.impl.module.complex.DefaultAmbulanceTargetAllocator` instead of the `sample_team.module.complex.SampleAmbulanceTargetAllocator`, you can replace the latter by the former in the `DefaultTacticsAmbulanceCentre.TargetAllocator` entry of the `config/module.cfg` file.

FROM
`DefaultTacticsAmbulanceCentre.TargetAllocator : sample_team.module.complex.SampleAmbulanceTargetAllocator`

TO
`DefaultTacticsAmbulanceCentre.TargetAllocator : adf.impl.module.complex.DefaultAmbulanceTargetAllocator`

The `adf-sample-agent-java` project depends on the `adf-core-java` project, so you can use the classes defined in the latter in the former without any problem.

Please let me know if you need any further information.

**Comment by gnardin** [comment] 2022-04-05 12:56
Dear @2661348402 
You must not modify the `adf-core-java` code. This repository and code are maintained by the Rescue Simulation team. Any change may be lost if you update to a newer version in the future. Besides, if you intend to participate in the competition, your changes in the `adf-core-java` will not exist since we use the version released on GitHub.

The `adf-core-java` is one library used in the `adf-sample-agent-java`. The `adf-core-java` is linked to the `adf-sample-agent-java` through the `dependencies` section of the `build.gradle` file in the `adf-sample-agent-java` repository. The exact dependency entry that creates the link is `implementation 'com.github.roborescue:rcrs-server:master-SNAPSHOT'`.

If you want to change some of the Default classes implemented in the `adf.impl`, you need to copy the classes from the `adf-core-java` to your team repository and make the necessary changes.

**NOTE**: Do not forget to change the info in the `config/module.cfg` in order to make ADF use your new class instead of using the default class.

The `adf-sample-agent-java` is an example of team. You can use it as a starting point to create your own team.

**Comment by 2661348402** [comment] 2022-04-10 02:00
When I try to run the project with idea, I can't find where the main class is, and when I try to use java.core.Main in external libraries as the main class and run， this error: Error: Could not find or load main class adf.core.Main
Caused by: java.lang.ClassNotFoundException: adf.core.Main
How can I solve this problem. external libraries
![图片](https://user-images.githubusercontent.com/80761477/162597785-80e8a4a3-df5d-4375-8f0b-4b738ce6a5fe.png)
@gnardin

**Comment by 2661348402** [comment] 2022-04-10 02:43
![图片](https://user-images.githubusercontent.com/80761477/162598707-26230f52-cd3c-4499-aee3-f1180dc3cdb7.png)
When I copy the adf file from adf-core-java to
adf-sample-agent-java src file, there is an error error: package javax.annotation does not exist import javax.annotation.Nonnull;
I found the answer on the Internet: java17 does not contain the javax package, so we need to add this package to the library, right?

**Comment by gnardin** [comment] 2022-04-10 20:43
Dear @2661348402 
To properly run the project, you need to use the Gradle `launch` task. You can try to replicate the configurations in the Gradle `launch` task in Idea IDE or you can make Idea IDE to call the Gradle `launch` task. I do not know Idea IDE to instruct you how to perform this configuration.

As I previously mentioned, you should not copy anything from the `adf.core` package into the `adf-sample-agent-java` repository. You should only copy `adf.impl` package code into the `adf-sample-agent-java`.

If you use the Gradle tasks released in the `adf-sample-agent-java` repository, you do not need to configure anything because it already links the `adf-sample-agent-java` and `adf-core-java` repositories taken into account the required external libraries.

**Comment by 2661348402** [comment] 2022-04-11 05:37
When I copy adf.impl package code into the adf-sample-agent-java, and run ./gradlew build, I get an error,
![Uploading 图片.png…]()
@gnardin

**Comment by gnardin** [comment] 2022-04-11 06:47
Dear @2661348402 
If you copy the `adf.impl`, you should also check if some dependencies required to be set in the `adf-sample-agent-java` repository.
Despite not providing detailed information of how you generated the error, I was able to figure this out and reproduce in my environment. To solve the problem, you can simply add the dependence entry `implementation 'com.google.common:google-collect:0.5'` in the `dependencies` section of the `build.gradle` file.

```
dependencies {
  ...
  implementation 'com.google.common:google-collect:0.5'
  ...
}
```

**Comment by gnardin** [comment] 2022-04-13 13:09
Dear @2661348402 
You can debug your ADF code by enabling the debugging feature on ADF by changing the debug flag `adf.debug.flag` from  `0` to `1` in the `config/launch.cfg` file. Or you can use the debugging features of your IDE.

I will close this issue. In case you have further questions, please open another specific issue. Please use a self-explanatory title to help others when they look for some information.

**Closed by gnardin** 2022-04-13 13:09 UTC
Labels: question
